name: Build and Test

on:
  push:
    branches: [ master, develop, 3.x, 3.x-dev, 4.x-dev ]
  pull_request:
    branches: [ master, develop, 3.x, 3.x-dev, 4.x-dev]

jobs:
  build:

    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: ['ubuntu-latest']
        php-versions: ['7.4']

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        extensions: mbstring, intl, mysqli, gd
        ini-values: post_max_size=256M, max_execution_time=180
        coverage: xdebug  
        tools: php-cs-fixer, phpunit 

    - name: Shutdown Ubuntu MySQL (SUDO)
      run: sudo service mysql stop # Shutdown the Default MySQL, "sudo" is necessary, please not remove it

    - name: Set up MySQL
      uses: mirromutth/mysql-action@v1.1
      with:
        host port: 3306 # Optional, default value is 3306. The port of host
        container port: 3306 # Optional, default value is 3306. The port of container
        character set server: 'utf8' # Optional, default value is 'utf8mb4'. The '--character-set-server' option for mysqld
        collation server: 'utf8_general_ci' # Optional, default value is 'utf8mb4_general_ci'. The '--collation-server' option for mysqld
        mysql version: '5.7' # Optional, default value is "latest". The version of the MySQL
        mysql database: 'dvelum_test' # Optional, default value is "test". The specified database which will be create
        #mysql root password: 'dvelum_test' # Required if "mysql user" is empty, default is empty. The root superuser password
        mysql user: 'dvelum_test' # Required if "mysql root password" is empty, default is empty. The superuser for the specified database. Can use secrets, too
        mysql password: 'dvelum_test' # Required if "mysql user" exists. The password for the "mysql user"

      # - name: Set up MySQL USER
      #   run: mysql -e 'GRANT ALL PRIVILEGES ON dvelum_test.* TO `dvelum_test`@'%' IDENTIFIED BY "dvelum_test";'

    - name: Validate composer.json and composer.lock
      run: composer validate
      
    - name: Install dependencies
      if: steps.composer-cache.outputs.cache-hit != 'true'
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Install ORM
      run: composer require dvelum/dvelum-orm:dev-develop

    - name: Enable ORM Extension
      run: php ./console.php /extension-add/dvelum/dvelum-orm

    - name: PHPStan tests
      run: php -d memory_limit=256M ./vendor/bin/phpstan analyse src ./tests/unit/dvelum extensions/dvelum/dvelum-orm/src
      
    - name: PHPUnit tests
      run: ./vendor/bin/phpunit -c ./integration.xml.dist --coverage-clover coverage.xml

    - name: Code Style check PHPCS
      run: php ./vendor/bin/phpcs --standard=PSR12 ./src ./application/classes ./tests/unit/dvelum

    - name: Code Style check PHPCS additional sniffs
      run: php ./vendor/bin/phpcs --standard=Squiz --sniffs=Squiz.NamingConventions.ValidVariableName ./src ./application/classes ./tests/unit/dvelum
      
    - name: Send Coverage report
      run: php vendor/bin/codacycoverage clover coverage.xml 
      env: 
         CODACY_PROJECT_TOKEN: ${{secrets.CODACY}}
